import { PermissionKey, PERMISSIONS } from "./permissions";

export type RoleDefinition = {
  key: string;
  name: string;
  description: string;
  isSystem: boolean;
  permissions: PermissionKey[];
};

export const SYSTEM_ROLES: RoleDefinition[] = [
  {
    key: "super_admin",
    name: "Super Admin",
    description: "Akses penuh ke seluruh modul sistem HRIS dan System Management",
    isSystem: true,
    permissions: PERMISSIONS.map((p) => p.key as PermissionKey),
  },
  {
    key: "admin_hr",
    name: "Admin HR",
    description: "Pengelolaan penuh modul HRIS (karyawan, absensi, cuti, payroll, kinerja, rekrutmen)",
    isSystem: true,
    permissions: [
      "hris.employee.read:all",
      "hris.employee.write:all",
      "hris.employee.import:all",
      "hris.org.manage:all",
      "hris.contract.read:all",
      "hris.contract.write:all",
      "hris.attendance.read:all",
      "hris.attendance.correct:all",
      "hris.attendance.checkin:own",
      "hris.leave.read:all",
      "hris.leave.approve:all",
      "hris.leave.configure:all",
      "hris.payroll.read:all",
      "hris.payroll.manage:all",
      "hris.payslip.read:own",
      "hris.performance.read:all",
      "hris.performance.manage:all",
      "hris.recruitment.read:all",
      "hris.recruitment.manage:all",
      "hris.training.read:all",
      "hris.training.manage:all",
      "sysmgmt.asset.read:all",
      "sysmgmt.document.read:all",
      "sysmgmt.document.manage:hr",
      "sysmgmt.document.read:own",
    ],
  },
  {
    key: "admin_it",
    name: "Admin IT",
    description: "Pengelolaan pengguna, role, inventaris aset, lisensi, dokumen & audit log",
    isSystem: true,
    permissions: [
      "hris.employee.read:all",
      "sysmgmt.dashboard.read:all",
      "sysmgmt.user.read:all",
      "sysmgmt.user.manage:all",
      "sysmgmt.role.read:all",
      "sysmgmt.role.manage:all",
      "sysmgmt.asset.read:all",
      "sysmgmt.asset.write:all",
      "sysmgmt.asset.import:all",
      "sysmgmt.license.read:all",
      "sysmgmt.license.manage:all",
      "sysmgmt.document.read:all",
      "sysmgmt.document.manage:all",
      "sysmgmt.audit.read:all",
      "sysmgmt.audit.export:all",
      "hris.attendance.checkin:own",
      "sysmgmt.asset.read:own",
      "sysmgmt.document.read:own",
    ],
  },
  {
    key: "manager",
    name: "Manajer / Atasan",
    description: "Persetujuan cuti tim, melihat kinerja & presensi bawahan langsung",
    isSystem: true,
    permissions: [
      "hris.employee.read:team",
      "hris.attendance.read:team",
      "hris.leave.read:team",
      "hris.leave.approve:team",
      "hris.performance.read:team",
      "hris.performance.review:team",
      "hris.recruitment.interview:team",
      "hris.training.read:team",
      "sysmgmt.document.read:team",
      // Personal items
      "hris.employee.read:own",
      "hris.employee.write:own",
      "hris.contract.read:own",
      "hris.attendance.read:own",
      "hris.attendance.checkin:own",
      "hris.leave.read:own",
      "hris.leave.create:own",
      "hris.leave.cancel:own",
      "hris.payslip.read:own",
      "hris.performance.read:own",
      "hris.performance.review:own",
      "hris.training.read:own",
      "sysmgmt.asset.read:own",
      "sysmgmt.document.read:own",
    ],
  },
  {
    key: "staff",
    name: "Karyawan (Staff)",
    description: "Akses mandiri (self-service) untuk data pribadi, presensi, cuti, slip gaji",
    isSystem: true,
    permissions: [
      "hris.employee.read:own",
      "hris.employee.write:own",
      "hris.contract.read:own",
      "hris.attendance.read:own",
      "hris.attendance.checkin:own",
      "hris.leave.read:own",
      "hris.leave.create:own",
      "hris.leave.cancel:own",
      "hris.payslip.read:own",
      "hris.performance.read:own",
      "hris.performance.review:own",
      "hris.training.read:own",
      "sysmgmt.asset.read:own",
      "sysmgmt.document.read:own",
    ],
  },
];
